#!/bin/bash
echo - removing the keys...
rm ~/.ssh/id_rsa* # it removes the keys so they'll be recreated
echo - regenerateing new keys as they are missing...
~/sshj-client/run.sh /home/petrum/.ssh/id_rsa
echo - appending the new pub key to the remote server...
~/sshj-client/deploykey.sh
echo - checking if new sshj created keys work with ssh...
ssh www.petrum.net -p 22223 uname
echo - checking the new keys from new created files...
~/sshj-client/run.sh /home/petrum/.ssh/id_rsa
echo - checking the keys from openssh backup files...
~/sshj-client/run.sh /home/petrum/.ssh/bak/id_rsa
echo - restoreing the backup files for normal usage...
cp -p ~/.ssh/bak/id* ~/.ssh
echo Done