#!/bin/bash

rm ~/.ssh/id_rsa* # it removes the keys so they'll be recreated
echo - this will just regenerate new keys as they are missing...
~/sshj-client/run.sh /home/petrum/.ssh/id_rsa
echo - it appends the new pub key to the remote server...
~/sshj-client/deploykey.sh
echo - it checks if new sshj created keys work with ssh...
ssh www.petrum.net -p 22223 uname
echo - it uses the new keys from new created files...
~/sshj-client/run.sh /home/petrum/.ssh/id_rsa
echo - it uses the keys from openssh backup files...
~/sshj-client/run.sh /home/petrum/.ssh/bak/id_rsa
echo - it restores the backup files for normal usage...
cp -p ~/.ssh/bak/id* ~/.ssh
echo Done